import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Introduction and Getting Started
  guideSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [{type: 'autogenerated', dirName: 'introduction'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Cookbook',
      items: [{type: 'autogenerated', dirName: 'cookbook'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },
  ],

  // Personality System (Primary Focus)
  personalitySidebar: [
    {
      type: 'category',
      label: 'Personality System',
      items: [{type: 'autogenerated', dirName: 'personality-system'}],
    },
  ],

  // SDK Integration
  sdkSidebar: [
    {
      type: 'category',
      label: 'SDK Integration',
      items: [{type: 'autogenerated', dirName: 'sdk-integration'}],
    },
  ],

  // API Reference
  apiSidebar: [
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api-reference'}],
    },
  ],
};

export default sidebars;
